/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliveRouteImport } from './routes/alive'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ImgIdRouteImport } from './routes/img.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliveRoute = AliveRouteImport.update({
  id: '/alive',
  path: '/alive',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgIdRoute = ImgIdRouteImport.update({
  id: '/img/$id',
  path: '/img/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alive': typeof AliveRoute
  '/charts': typeof ChartsRoute
  '/events': typeof EventsRoute
  '/img/$id': typeof ImgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alive': typeof AliveRoute
  '/charts': typeof ChartsRoute
  '/events': typeof EventsRoute
  '/img/$id': typeof ImgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alive': typeof AliveRoute
  '/charts': typeof ChartsRoute
  '/events': typeof EventsRoute
  '/img/$id': typeof ImgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alive' | '/charts' | '/events' | '/img/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alive' | '/charts' | '/events' | '/img/$id'
  id: '__root__' | '/' | '/alive' | '/charts' | '/events' | '/img/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliveRoute: typeof AliveRoute
  ChartsRoute: typeof ChartsRoute
  EventsRoute: typeof EventsRoute
  ImgIdRoute: typeof ImgIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alive': {
      id: '/alive'
      path: '/alive'
      fullPath: '/alive'
      preLoaderRoute: typeof AliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$id': {
      id: '/img/$id'
      path: '/img/$id'
      fullPath: '/img/$id'
      preLoaderRoute: typeof ImgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliveRoute: AliveRoute,
  ChartsRoute: ChartsRoute,
  EventsRoute: EventsRoute,
  ImgIdRoute: ImgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
