/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: a8a6bb7dfa4f5f5b472288bb369ed4e2)
interface __BaseEnv_Env {
	DB: D1Database;
	RATE_LIMITER: RateLimit;
	MAX_EVENTS_PER_DAY: string;
	MAX_BYTES_PER_DAY: string;
	MAX_COHORT_EVENTS_PER_DAY: string;
	MAX_DB_BYTES: string;
	RETENTION_DAYS: string;
	RETENTION_DELETE_ROWS_PER_RUN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_EVENTS_PER_DAY" | "MAX_BYTES_PER_DAY" | "MAX_COHORT_EVENTS_PER_DAY" | "MAX_DB_BYTES" | "RETENTION_DAYS" | "RETENTION_DELETE_ROWS_PER_RUN">> {}
}
