/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: d758c1639ed19df6209af50b19eba4ec)
interface __BaseEnv_Env {
	DB: D1Database;
	RATE_LIMITER: RateLimit;
	MAX_EVENTS_PER_DAY: string;
	MAX_BYTES_PER_DAY: string;
	MAX_COHORT_EVENTS_PER_DAY: string;
	MAX_STORED_EVENTS: string;
	RETENTION_DAYS: string;
	RETENTION_DELETE_ROWS_PER_RUN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_EVENTS_PER_DAY" | "MAX_BYTES_PER_DAY" | "MAX_COHORT_EVENTS_PER_DAY" | "MAX_STORED_EVENTS" | "RETENTION_DAYS" | "RETENTION_DELETE_ROWS_PER_RUN">> {}
}
